export const KE_BANKS = [
  { code: 'ABK', name: 'ABC Bank Kenya' },
  { code: 'ABSA', name: 'ABSA Bank Kenya' },
  { code: 'ACCESS', name: 'Access Bank Kenya' },
  { code: 'BOA', name: 'Bank of Africa Kenya' },
  { code: 'BOB', name: 'Bank of Baroda Kenya' },
  { code: 'BOI', name: 'Bank of India Kenya' },
  { code: 'CITI', name: 'Citibank Kenya' },
  { code: 'CONSO', name: 'Consolidated Bank Kenya' },
  { code: 'COOP', name: 'Co-operative Bank of Kenya' },
  { code: 'CBA', name: 'Commercial Bank of Africa' },
  { code: 'CRAFT', name: 'Credit Bank' },
  { code: 'DTB', name: 'Diamond Trust Bank Kenya' },
  { code: 'DIB', name: 'DIB Bank Kenya' },
  { code: 'ECOB', name: 'Ecobank Kenya' },
  { code: 'EQTY', name: 'Equity Bank Kenya' },
  { code: 'FAMB', name: 'Family Bank' },
  { code: 'FCB', name: 'First Community Bank' },
  { code: 'GTBK', name: 'Guaranty Trust Bank Kenya' },
  { code: 'GULF', name: 'Gulf African Bank' },
  { code: 'HFCK', name: 'Housing Finance Company of Kenya' },
  { code: 'IMB', name: 'I&M Bank Kenya' },
  { code: 'KCB', name: 'Kenya Commercial Bank' },
  { code: 'KWFT', name: 'Kenya Women Microfinance Bank' },
  { code: 'MARA', name: 'Mayfair CIB Bank' },
  { code: 'MIDB', name: 'Middle East Bank Kenya' },
  { code: 'NBK', name: 'National Bank of Kenya' },
  { code: 'NCBA', name: 'NCBA Bank Kenya' },
  { code: 'ORIENT', name: 'Oriental Commercial Bank' },
  { code: 'PARAMOUNT', name: 'Paramount Bank' },
  { code: 'PRIME', name: 'Prime Bank Kenya' },
  { code: 'SBM', name: 'SBM Bank Kenya' },
  { code: 'SCB', name: 'Standard Chartered Bank Kenya' },
  { code: 'SIDIAN', name: 'Sidian Bank' },
  { code: 'SPIRE', name: 'Spire Bank' },
  { code: 'STANBIC', name: 'Stanbic Bank Kenya' },
  { code: 'UBA', name: 'United Bank for Africa Kenya' },
  { code: 'VICTORIA', name: 'Victoria Commercial Bank' },
] as const;
